# Generated by Django 6.0.4 on 2026-05-07 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turag', '0008_alter_tour_persons'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='comments',
        ),
    ]
