# Generated by Django 6.0.4 on 2026-05-13 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turag', '0010_tour_image_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='image',
        ),
        migrations.AddField(
            model_name='tour',
            name='image_url',
            field=models.URLField(default='', max_length=500, verbose_name='Ссылка на фото товара'),
        ),
    ]
