# Generated by Django 6.0.4 on 2026-05-19 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turag', '0011_remove_tour_image_tour_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeaderSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Настройки шапки', editable=False, max_length=100)),
                ('background_image', models.ImageField(upload_to='header_bg/', verbose_name='Фоновое изображение шапки')),
            ],
            options={
                'verbose_name': 'Настройки шапки',
                'verbose_name_plural': 'Настройки шапки',
            },
        ),
    ]
