# Generated by Django 6.0.4 on 2026-05-19 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turag', '0013_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headersettings',
            name='background_image',
            field=models.ImageField(upload_to='headers/', verbose_name='Фоновое изображение шапки'),
        ),
    ]
