# Generated by Django 6.0.4 on 2026-05-29 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turag', '0014_alter_headersettings_background_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='review_photos/', verbose_name='Фото к отзыву'),
        ),
    ]
