# Generated by Django 6.0.4 on 2026-05-29 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turag', '0015_review_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='booked_slots',
            field=models.PositiveIntegerField(default=0, verbose_name='Занято мест'),
        ),
        migrations.AddField(
            model_name='tour',
            name='total_slots',
            field=models.PositiveIntegerField(default=20, verbose_name='Всего мест'),
        ),
    ]
