# Generated by Django 6.0.4 on 2026-05-29 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turag', '0016_tour_booked_slots_tour_total_slots'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='duration',
        ),
    ]
