# Generated by Django 6.0.4 on 2026-05-29 22:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turag', '0017_remove_tour_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='cost_for_one_person',
            field=models.DecimalField(decimal_places=2, max_digits=10, max_length=10, validators=[django.core.validators.MinValueValidator(0, message='Цена тура не может быть отрицательной!')], verbose_name='Стоимость за одного человека'),
        ),
    ]
