# Generated by Django 6.0.4 on 2026-05-29 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turag', '0018_alter_tour_cost_for_one_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='date_end',
            field=models.DateTimeField(verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='date_start',
            field=models.DateTimeField(verbose_name='Дата начала'),
        ),
    ]
