# Generated by Django 6.0.4 on 2026-05-29 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turag', '0019_alter_tour_date_end_alter_tour_date_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название тура'),
        ),
    ]
