# Generated by Django 6.0.4 on 2026-05-31 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turag', '0022_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
