# Generated by Django 6.0.4 on 2026-05-31 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turag', '0023_delete_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'verbose_name': 'Бронирование', 'verbose_name_plural': 'Бронирования'},
        ),
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'В обработке (ожидает подтверждения)'), ('confirmed', 'Подтвержден (билеты выписываются)'), ('ready', 'Документы готовы (выписаны)'), ('cancelled', 'Отменен')], default='pending', max_length=20, verbose_name='Статус заказа'),
        ),
        migrations.AddField(
            model_name='booking',
            name='tickets_file',
            field=models.FileField(blank=True, null=True, upload_to='tickets/', verbose_name='Файл билетов/ваучеров (PDF)'),
        ),
    ]
