# Generated by Django 6.0.4 on 2026-05-31 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turag', '0024_alter_booking_options_booking_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='services',
            field=models.TextField(default=''),
        ),
    ]
