# Generated by Django 6.0.4 on 2026-05-31 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turag', '0025_tour_services'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='image_url',
        ),
        migrations.AddField(
            model_name='tour',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tours/', verbose_name='Фото тура'),
        ),
        migrations.AddField(
            model_name='tour',
            name='slug',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='URL-слаг'),
        ),
    ]
