# Generated by Django 6.0.4 on 2026-05-31 18:45

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turag', '0026_remove_tour_image_url_tour_image_tour_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='', editable=False, populate_from='name', unique=True, verbose_name='URL-слаг'),
        ),
    ]
