# Generated by Django 6.0.4 on 2026-06-02 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turag', '0027_alter_tour_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addservice',
            options={'verbose_name': 'дополнительная услуга', 'verbose_name_plural': 'дополнительные услуги'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'комментарий', 'verbose_name_plural': 'комментарии'},
        ),
        migrations.AlterModelOptions(
            name='headersettings',
            options={'verbose_name': 'настройки шапки'},
        ),
        migrations.AlterModelOptions(
            name='hotel',
            options={'verbose_name': 'отель', 'verbose_name_plural': 'отели'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'заказ', 'verbose_name_plural': 'заказы'},
        ),
        migrations.AlterModelOptions(
            name='program',
            options={'verbose_name': 'программа', 'verbose_name_plural': 'программы'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'отзыв', 'verbose_name_plural': 'отзывы'},
        ),
        migrations.AlterModelOptions(
            name='tour',
            options={'verbose_name': 'тур', 'verbose_name_plural': 'туры'},
        ),
        migrations.AlterModelOptions(
            name='touroperator',
            options={'verbose_name': 'туроператор', 'verbose_name_plural': 'туроператоры'},
        ),
        migrations.AlterModelOptions(
            name='transport',
            options={'verbose_name': 'транспорт', 'verbose_name_plural': 'транспорт'},
        ),
        migrations.CreateModel(
            name='TourImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='tours/gallery/', verbose_name='Изображение')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='turag.tour', verbose_name='Тур')),
            ],
            options={
                'verbose_name': 'Фотография тура',
                'verbose_name_plural': 'Фотографии тура',
            },
        ),
    ]
