# Generated by Django 6.0.4 on 2026-06-02 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turag', '0028_alter_addservice_options_alter_comment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='services',
            field=models.TextField(blank=True, default=''),
        ),
    ]
