# Generated by Django 6.0.4 on 2026-06-02 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turag', '0030_booking_services_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
